In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('./uber_data.csv')

In [3]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               100000 non-null  int64
 1   tpep_pickup_datetime   100000 non-null  object
 2   tpep_dropoff_datetime  100000 non-null  object
 3   passenger_count        100000 non-null  int64
 4   trip_distance          100000 non-null  float64
 5   pickup_longitude       100000 non-null  float64
 6   pickup_latitude        100000 non-null  float64
 7   RatecodeID             100000 non-null  int64
 8   store_and_fwd_flag     100000 non-null  object
 9   dropoff_longitude      100000 non-null  float64
 10  dropoff_latitude       100000 non-null  float64
 11  payment_type           100000 non-null  int64
 12  fare_amount            100000 non-null  float64
 13  extra                  100000 non-null  float64
 14  mta_tax                100000 non-null  float64
 15  tip_amount             100000 non-null  float64
 16  tolls_amount           100000 non-null  float64
 17  improvement_surcharge  100000 non-null  float64
 18  total_amount           100000 non-null  float64
dtypes: float64(12), int64(4), object(3)
memory usage: 14.5+ MB

In [4]:
df['tpep_pickup_datetime'].nunique()

38332

In [6]:
df['passenger_count'].nunique()

7

In [7]:
df['trip_distance'].nunique()

2303

In [8]:
df['payment_type'].nunique()

4

In [9]:
df['RatecodeID'].nunique()

6

In [10]:
df['store_and_fwd_flag'].nunique()

2

In [12]:
df['mta_tax'].nunique()

3

In [17]:
datetime_dim = df[['tpep_pickup_datetime','tpep_dropoff_datetime']].drop_duplicates().reset_index(drop=True)

In [18]:
datetime_dim.head()

  tpep_pickup_datetime tpep_dropoff_datetime
0  2016-03-01 00:00:00   2016-03-01 00:07:55
1  2016-03-01 00:00:00   2016-03-01 00:11:06
2  2016-03-01 00:00:00   2016-03-01 00:31:06
3  2016-03-01 00:00:00   2016-03-01 00:00:00
4  2016-03-01 00:00:01   2016-03-01 00:16:04

In [37]:
df['tpep_pickup_datetime']=pd.to_datetime(df['tpep_pickup_datetime'])
df['tpep_dropoff_datetime']=pd.to_datetime(df['tpep_dropoff_datetime'])

In [20]:
datetime_dim['tpep_pickup_datetime']=pd.to_datetime(datetime_dim['tpep_pickup_datetime'])
datetime_dim['tpep_dropoff_datetime']=pd.to_datetime(datetime_dim['tpep_dropoff_datetime'])
datetime_dim['pick_day']=datetime_dim['tpep_pickup_datetime'].dt.day
datetime_dim['pick_month']=datetime_dim['tpep_pickup_datetime'].dt.month
datetime_dim['pick_year']=datetime_dim['tpep_pickup_datetime'].dt.year
datetime_dim['pick_weekday']=datetime_dim['tpep_pickup_datetime'].dt.weekday
datetime_dim['pick_hour']=datetime_dim['tpep_pickup_datetime'].dt.hour
datetime_dim['drop_day']=datetime_dim['tpep_dropoff_datetime'].dt.day
datetime_dim['drop_month']=datetime_dim['tpep_dropoff_datetime'].dt.month
datetime_dim['drop_year']=datetime_dim['tpep_dropoff_datetime'].dt.year
datetime_dim['drop_weekday']=datetime_dim['tpep_dropoff_datetime'].dt.weekday
datetime_dim['drop_hour']=datetime_dim['tpep_dropoff_datetime'].dt.hour

In [25]:
datetime_dim.drop('datetime_id',axis=1,inplace=True)
datetime_dim.insert(0,'datetime_id',datetime_dim.index)

In [26]:
datetime_dim.head()

,datetime_id,tpep_pickup_datetime,tpep_dropoff_datetime,pick_day,pick_month,pick_year,pick_weekday,pick_hour,drop_day,drop_month,drop_year,drop_weekday,drop_hour
0,0,2016-03-01 00:00:00,2016-03-01 00:07:55,1,3,2016,1,0,1,3,2016,1,0
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,3,2016,1,0,1,3,2016,1,0
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,1,3,2016,1,0,1,3,2016,1,0
3,3,2016-03-01 00:00:00,2016-03-01 00:00:00,1,3,2016,1,0,1,3,2016,1,0
4,4,2016-03-01 00:00:01,2016-03-01 00:16:04,1,3,2016,1,0,1,3,2016,1,0

In [27]:
pickup_location_dim=df[['pickup_longitude','pickup_latitude']].drop_duplicates().reset_index(drop=True)
pickup_location_dim.insert(0,'pickup_location_id',pickup_location_dim.index)
pickup_location_dim.head()

   pickup_location_id  pickup_longitude  pickup_latitude
0                   0        -73.976746        40.765152
1                   1        -73.983482        40.767925
2                   2        -73.782021        40.644810
3                   3        -73.863419        40.769814
4                   4        -73.971741        40.792183

In [28]:
dropoff_location_dim=df[['dropoff_longitude','dropoff_latitude']].drop_duplicates().reset_index(drop=True)
dropoff_location_dim.insert(0,'dropoff_location_id',dropoff_location_dim.index)
dropoff_location_dim.head()

   dropoff_location_id  dropoff_longitude  dropoff_latitude
0                    0         -74.004265         40.746128
1                    1         -74.005943         40.733166
2                    2         -73.974541         40.675770
3                    3         -73.969650         40.757767
4                    4         -74.177170         40.695053

In [31]:
passenger_count_dim=df[['passenger_count']].drop_duplicates().reset_index(drop=True)
passenger_count_dim.insert(0,'passenger_count_id',passenger_count_dim.index)
passenger_count_dim.head()

   passenger_count_id  passenger_count
0                   0                1
1                   1                2
2                   2                3
3                   3                5
4                   4                6

In [32]:
trip_distance_dim=df[['trip_distance']].drop_duplicates().reset_index(drop=True)
trip_distance_dim.insert(0,'trip_distance_id',trip_distance_dim.index)
trip_distance_dim.head()

   trip_distance_id  trip_distance
0                 0           2.50
1                 1           2.90
2                 2          19.98
3                 3          10.78
4                 4          30.43

In [33]:
rate_code_dim=df[['RatecodeID']].drop_duplicates().reset_index(drop=True)
rate_code_dim.insert(0,'rate_code_id',rate_code_dim.index)
rate_code_dim.head()

   rate_code_id  RatecodeID
0             0           1
1             1           3
2             2           2
3             3           5
4             4           4

In [34]:
store_and_fwd_flag_dim=df[['store_and_fwd_flag']].drop_duplicates().reset_index(drop=True)
store_and_fwd_flag_dim.insert(0,'store_and_fwd_flag_id',store_and_fwd_flag_dim.index)
store_and_fwd_flag_dim.head()

   store_and_fwd_flag_id store_and_fwd_flag
0                      0                  N
1                      1                  Y

In [35]:
payment_type_dim=df[['payment_type']].drop_duplicates().reset_index(drop=True)
payment_type_dim.insert(0,'payment_type_id',payment_type_dim.index)
payment_type_dim.head()

   payment_type_id  payment_type
0                0             1
1                1             2
2                2             3
3                3             4

In [40]:
fact_table = df.merge(datetime_dim, on=['tpep_pickup_datetime', 'tpep_dropoff_datetime']) \
              .merge(passenger_count_dim, on='passenger_count') \
              .merge(trip_distance_dim, on='trip_distance') \
              .merge(rate_code_dim, on='RatecodeID') \
              .merge(pickup_location_dim, on=['pickup_longitude', 'pickup_latitude']) \
              .merge(dropoff_location_dim, on=['dropoff_longitude', 'dropoff_latitude']) \
              .merge(payment_type_dim, on='payment_type') \
              .merge(store_and_fwd_flag_dim, on='store_and_fwd_flag')

In [41]:
fact_table=fact_table[['VendorID','datetime_id','passenger_count_id','trip_distance_id','pickup_location_id','dropoff_location_id','rate_code_id','store_and_fwd_flag_id','payment_type_id','fare_amount','extra','mta_tax','tip_amount','tolls_amount','improvement_surcharge','total_amount']]

In [42]:
fact_table.head()

,VendorID,datetime_id,passenger_count_id,trip_distance_id,pickup_location_id,dropoff_location_id,rate_code_id,store_and_fwd_flag_id,payment_type_id,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,0,0,0,0,0,0,0,0,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,1,0,1,1,1,0,0,0,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2,1,2,2,2,0,0,0,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,3,2,3,3,3,0,0,0,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,3,3,4,4,4,1,0,0,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [43]:
datetime_dim.to_csv('./datetime_dim.csv',index=False)
pickup_location_dim.to_csv('./pickup_location_dim.csv',index=False)
dropoff_location_dim.to_csv('./dropoff_location_dim.csv',index=False)
passenger_count_dim.to_csv('./passenger_count_dim.csv',index=False)
trip_distance_dim.to_csv('./trip_distance_dim.csv',index=False)
rate_code_dim.to_csv('./rate_code_dim.csv',index=False)
store_and_fwd_flag_dim.to_csv('./store_and_fwd_flag_dim.csv',index=False)
payment_type_dim.to_csv('./payment_type_dim.csv',index=False)
fact_table.to_csv('./fact_table.csv',index=False)